{
  "cover_image_id": null,
  "created_at": "2025-10-21T07:55:52.744593Z",
  "description": null,
  "hero_image_id": null,
  "id": "demo_gallery_2",
  "options": {},
  "sort_order": 0,
  "summary": null,
  "tags": [],
  "title": "Demo Gallery 2",
  "updated_at": "2025-10-21T07:55:52.744593Z",
  "version": 1
}
