repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==2.12.3
          - pydantic-core==2.41.4
          - types-PyYAML
  # Run pytest as a local hook (not a remote repo)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python tools/run_pytest.py
        language: system
        types: [python]
        pass_filenames: false
