{
  "version": 1,
  "id": "demo-gallery-1",
  "title": "Demo Gallery 1 - Cars",
  "summary": "AI generated pictures of old abandoned cars.",
  "description": "AI generated pictures of old abandoned cars.",
  "tags": ["classic cars","cars","abandoned","decayed","rusted","dirt roads","ai photograph","photograph"],
  "sort_order": 0,
  "created_at": "2025-10-21T07:16:40Z",
  "updated_at": "2025-10-21T07:16:40Z",
  "cover_image_id": ce22cecb-63a8-4580-bdaf-fd23951484b9,
  "hero_image_id": 80123f41-1adc-45de-aaf3-4744745f90cd,
  "options": {}
}
