{
  "cover_image_id": null,
  "created_at": "2025-10-14T02:43:23.701435Z",
  "description": null,
  "hero_image_id": null,
  "id": "painted-landscapes",
  "options": {},
  "sort_order": 0,
  "summary": null,
  "tags": [],
  "title": "Painted Landscapes",
  "updated_at": "2025-10-14T02:43:23.701435Z",
  "version": 1
}
