title: "Painted Landscapes"
summary: "A collection of moody painted vistas captured on dusk walks."
description: |
  This gallery pulls together evolving concept art and photographic
  studies that explore light, color, and atmosphere across sprawling
  landscapes.
tags:
  - landscapes
  - concept-art
  - evening
status: published
published_at: 2025-09-21T18:30:00
hero: misty-trails.jpg
assets:
  misty-trails.jpg:
    alt_text: "Soft light spilling through a mountain pass."
  sunset-ridge.png:
    alt_text: "Orange ridge line fading into evening clouds."
  twilight-grove.png:
    alt_text: "Dense forest with painted lavender skies."
