name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
          python -m pip install .[gui]

      - name: Lint with Ruff
        run: ruff check .

      - name: Type-check with mypy
        run: mypy build

      - name: Run tests
        run: pytest
